### ISSUE TITLE
Disable Windows warnings? 

### ISSUE THREAD

**Issue by traversaro** [robotology/blocktest#40]
Hi everyone, 
   manipulating Windows CI logs in the robotology-superbuild is quite complex, mainly because of the size: a normal run of the Windows CI result in an output of ~170 MB. That log contains ~450k lines, and 250k of them contains the string "blocktest": 
~~~
STraversaro@IITICUBLAP102 MINGW64 ~/Downloads
$ cat 15_Build\ \(Release\)\ \[Windows\].txt | wc -l
452094
STraversaro@IITICUBLAP102 MINGW64 ~/Downloads
$ cat 15_Build\ \(Release\)\ \[Windows\].txt | grep blocktest | wc -l
258995
~~~
Navigating such a huge log is quite complicated. If no one is ever going to tackle the blocktest warning on Windows, could it make sense to simply disable it or to have at least an option to disable them?

**Comment by traversaro** [comment]
Friendly ping @triccyx @Nicogene

**Comment by triccyx** [comment]
@traversaro With
> blocktest warning on Windows

Do you mean compilation/linking warning on Windows?

**Comment by Nicogene** [comment]
Sorry for the late reply, I opened a PR in that sense, by default I kept them enabled, otherwise we forget about it.

**Comment by traversaro** [comment]
> 
> 
> @traversaro With
> 
> > blocktest warning on Windows
> 
> Do you mean compilation/linking warning on Windows?

Yes.

**Comment by traversaro** [comment]
I think we may have the same problem on blocktest-yarp-plugins repo.

**Comment by Nicogene** [comment]
Done here https://github.com/robotology/blocktest-yarp-plugins/commit/2922737059a9a051e855b422b5d9acce1bfc1b4d
