### ISSUE TITLE
Do a new release?

### ISSUE THREAD

**Issue by traversaro** [robotology/blocktest#46]
In view of the distro release 2021.02  of the superbuild, it would be convenient to have a new (even patch) release of this repo, including the fix https://github.com/robotology/blocktest/pull/44/files . 

cc @Nicogene @triccyx

**Comment by Nicogene** [comment]
Ok for me!
I will do a patch release

**Comment by Nicogene** [comment]
Here is the latest release https://github.com/robotology/blocktest/releases/tag/v2.3.1

Closing

**Comment by traversaro** [comment]
Thanks!
