### ISSUE TITLE
New patch release containing compatibility with latest Boost 1.76?

### ISSUE THREAD

**Issue by traversaro** [robotology/blocktest#49]
It would be convenient to have a release that contains https://github.com/robotology/blocktest/pull/48 to ensure that the 2021.05 release of the superbuild works fine on macOS/Homebrew, and that we don't have strange surprises as soon as conda-forge completes the migration to boost 1.76 .

**Comment by Nicogene** [comment]
Release delivered: https://github.com/robotology/blocktest/releases/tag/v2.3.2
